version: '3'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy:0.8.0
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      nginx-proxy:
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - certs:/etc/nginx/certs:ro
      - html:/usr/share/nginx/html
      - vhostd:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt:
    container_name: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    networks:
      nginx-proxy:
    restart: unless-stopped
    volumes:
      - certs:/etc/nginx/certs:rw
      - html:/usr/share/nginx/html
      - vhostd:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro

  www:
    container_name: www
    image: nginx
    depends_on:
      - letsencrypt
      - nginx-proxy
    environment:
      - LETSENCRYPT_HOST=jmac.tk
      - LETSENCRYPT_EMAIL=jhonatan.macazana147@gmail.com
      - VIRTUAL_HOST=jmac.tk
    expose:
      - "80"
    networks:
      nginx-proxy:
    restart: unless-stopped
    volumes:
      - ./www:/usr/share/nginx/html:ro

volumes: 
  certs:
  html:
  vhostd:

networks:
  nginx-proxy:
    name: nginx-proxy
