version: "3"
services:
  postgres:
    container_name: postgres_db
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    image: postgres:13.1-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
